<a href="https://colab.research.google.com/github/shane-SL/team_4/blob/main/totaltrain.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


## 讀取 google drive圖檔 :

In [ ]:
import glob
# GP125
gp = glob.glob("/content/drive/MyDrive/Tebame_第四組_機車辨識/原始照片(含外拍及網路)/KYMCO_GP/*.jpg") + glob.glob("/content/drive/MyDrive/Tebame_第四組_機車辨識/裁剪照片(不含不用裁的)/KYMCO_GP_125_裁/*.jpg") 

# 活力 125 原始+ 裁
vivo = glob.glob("/content/drive/MyDrive/Tebame_第四組_機車辨識/原始照片(含外拍及網路)/SYM_活力/*.jpg") + glob.glob("/content/drive/MyDrive/Tebame_第四組_機車辨識/裁剪照片(不含不用裁的)/SYM_活力_125_裁/*.jpg")

# 勁戰六代 原始+ 裁
gryphus6 = glob.glob("/content/drive/MyDrive/Tebame_第四組_機車辨識/原始照片(含外拍及網路)/YAMAHA_六代競戰/*.jpg") + glob.glob("/content/drive/MyDrive/Tebame_第四組_機車辨識/裁剪照片(不含不用裁的)/YAMAHA_六代勁戰_125_裁/*.jpg")

# SYM JET SR  ...
SR = glob.glob("/content/drive/MyDrive/Tebame_第四組_機車辨識/原始照片(含外拍及網路)/SYM_JET_SR/*.jpg") + glob.glob("/content/drive/MyDrive/Tebame_第四組_機車辨識/裁剪照片(不含不用裁的)/SYM_JET_SR_125_裁/*.jpg")

# SYM JET SL  ...
SL = glob.glob("/content/drive/MyDrive/Tebame_第四組_機車辨識/原始照片(含外拍及網路)/SYM_JET_SL/*.jpg") + glob.glob("/content/drive/MyDrive/Tebame_第四組_機車辨識/裁剪照片(不含不用裁的)/SYM_JET_SL_125_裁/*.jpg")

# YAMAHA JOG  ...
JOG = glob.glob("/content/drive/MyDrive/Tebame_第四組_機車辨識/原始照片(含外拍及網路)/YAMAHA_JOG/*.jpg") + glob.glob("/content/drive/MyDrive/Tebame_第四組_機車辨識/裁剪照片(不含不用裁的)/YAMAHA_JOG_125_裁/*.jpg")

# YAMAHA BWS  ...
BWS = glob.glob("/content/drive/MyDrive/Tebame_第四組_機車辨識/原始照片(含外拍及網路)/YAMAHA_BWS/*.jpg") + glob.glob("/content/drive/MyDrive/Tebame_第四組_機車辨識/裁剪照片(不含不用裁的)/YAMAHA_BWS_125_裁/*.jpg")

# YAMAHA LIMI  ...
LIMI = glob.glob("/content/drive/MyDrive/Tebame_第四組_機車辨識/原始照片(含外拍及網路)/YAMAHA_LIMI/*.jpg") + glob.glob("/content/drive/MyDrive/Tebame_第四組_機車辨識/裁剪照片(不含不用裁的)/YAMAHA_LIMI_125_已裁減/*.jpg")

# KYMCO LIKE
LIKE = glob.glob("/content/drive/MyDrive/Tebame_第四組_機車辨識/原始照片(含外拍及網路)/KYMCO_LIKE/*.jpg") + glob.glob("/content/drive/MyDrive/Tebame_第四組_機車辨識/裁剪照片(不含不用裁的)/KYMCO_LIKE_125_裁/*.jpg")

# DRG
DRG = glob.glob("/content/drive/MyDrive/Tebame_第四組_機車辨識/原始照片(含外拍及網路)/SYM_DRG/*.jpg") + glob.glob("/content/drive/MyDrive/Tebame_第四組_機車辨識/裁剪照片(不含不用裁的)/SYM_DRG_裁/*.jpg") 

# FIDDLE
FIDDLE = glob.glob("/content/drive/MyDrive/Tebame_第四組_機車辨識/原始照片(含外拍及網路)/SYM_FIDDLE/*.jpg") + glob.glob("/content/drive/MyDrive/Tebame_第四組_機車辨識/裁剪照片(不含不用裁的)/SYM_FIDDLE_125_裁/*.jpg") 

# gogoro S2
S2 = glob.glob("/content/drive/MyDrive/Tebame_第四組_機車辨識/原始照片(含外拍及網路)/GOGORO_S2/*.jpg") + glob.glob("/content/drive/MyDrive/Tebame_第四組_機車辨識/裁剪照片(不含不用裁的)/GOGORO_S2_裁/*.jpg")

# gogoro S3
S3 = glob.glob("/content/drive/MyDrive/Tebame_第四組_機車辨識/原始照片(含外拍及網路)/GOGORO_S3/*.jpg") + glob.glob("/content/drive/MyDrive/Tebame_第四組_機車辨識/裁剪照片(不含不用裁的)/GOGORO_S3_裁/*.jpg")

# gogoro VIVA_MIX
VIVAMIX = glob.glob("/content/drive/MyDrive/Tebame_第四組_機車辨識/原始照片(含外拍及網路)/GOGORO_VIVA_MIX/*.jpg") + glob.glob("/content/drive/MyDrive/Tebame_第四組_機車辨識/裁剪照片(不含不用裁的)/GOGORO_VIVA_MIX_裁/*.jpg")

# 新名流125
xml125 = glob.glob("/content/drive/MyDrive/Tebame_第四組_機車辨識/原始照片(含外拍及網路)/KYMCO_新名流/*.jpg") + glob.glob("/content/drive/MyDrive/Tebame_第四組_機車辨識/裁剪照片(不含不用裁的)/KYMCO_新名流125_裁/*.jpg")

# YAMAHA 勁豪
JH = glob.glob("/content/drive/MyDrive/Tebame_第四組_機車辨識/原始照片(含外拍及網路)/YAMAHA_勁豪/*.jpg") + glob.glob("/content/drive/MyDrive/Tebame_第四組_機車辨識/裁剪照片(不含不用裁的)/YAMAHA_勁豪_125_裁/*.jpg")

# KRV
KRV = glob.glob("/content/drive/MyDrive/Tebame_第四組_機車辨識/原始照片(含外拍及網路)/KYMCO_KRV/*.jpg") + glob.glob("/content/drive/MyDrive/Tebame_第四組_機車辨識/裁剪照片(不含不用裁的)/KYMCO_KRV_裁/*.jpg")

# KYMCO MANY
MANY = glob.glob("/content/drive/MyDrive/Tebame_第四組_機車辨識/原始照片(含外拍及網路)/KYMCO_MANY/*.jpg") + glob.glob("/content/drive/MyDrive/Tebame_第四組_機車辨識/裁剪照片(不含不用裁的)/KYMCO_MANY_125_裁/*.jpg")

# YAMAHA FORCE
Force = glob.glob("/content/drive/MyDrive/Tebame_第四組_機車辨識/原始照片(含外拍及網路)/YAMAHA_FORCE/*.jpg") + glob.glob("/content/drive/MyDrive/Tebame_第四組_機車辨識/裁剪照片(不含不用裁的)/YAMAHA_FORCE_裁/*.jpg") + glob.glob("/content/drive/MyDrive/Tebame_第四組_機車辨識/原始照片(含外拍及網路)/YAMAHA_FORCE/*.JPG") + glob.glob("/content/drive/MyDrive/Tebame_第四組_機車辨識/裁剪照片(不含不用裁的)/YAMAHA_FORCE_裁/*.JPG")

# SYM 新迪爵
xdj = glob.glob("/content/drive/MyDrive/Tebame_第四組_機車辨識/原始照片(含外拍及網路)/SYM_新迪爵/*.jpg") + glob.glob("/content/drive/MyDrive/Tebame_第四組_機車辨識/裁剪照片(不含不用裁的)/SYM_新迪爵_125 _裁/*.jpg")



In [ ]:
import pandas as pd
df = pd.DataFrame({
    "path": gp + vivo + gryphus6 + SR + SL + JOG + BWS + LIMI + LIKE + DRG + FIDDLE + S2 + S3 + VIVAMIX + xml125 + JH + KRV + MANY + Force +xdj,
    "ans": [0] * len(gp) + [1] * len(vivo) + [2] * len(gryphus6) + [3] * len(SR) + [4] * len(SL) + [5] * len(JOG) + [6] * len(BWS) + [7] * len(LIMI) + [8] * len(LIKE) + [9] * len(DRG) + [10] * len(FIDDLE) + [11] * len(S2) + [12] * len(S3) + [13] * len(VIVAMIX) + [14] * len(xml125) + [15] * len(JH) + [16] * len(KRV) + [17] * len(MANY) + [18] * len(Force) + [19] * len(xdj)
})
df

path  ans
0      /content/drive/MyDrive/Tebame_第四組_機車辨識/原始照片(含外...    0
1      /content/drive/MyDrive/Tebame_第四組_機車辨識/原始照片(含外...    0
2      /content/drive/MyDrive/Tebame_第四組_機車辨識/原始照片(含外...    0
3      /content/drive/MyDrive/Tebame_第四組_機車辨識/原始照片(含外...    0
4      /content/drive/MyDrive/Tebame_第四組_機車辨識/原始照片(含外...    0
...                                                  ...  ...
11343  /content/drive/MyDrive/Tebame_第四組_機車辨識/裁剪照片(不含...   19
11344  /content/drive/MyDrive/Tebame_第四組_機車辨識/裁剪照片(不含...   19
11345  /content/drive/MyDrive/Tebame_第四組_機車辨識/裁剪照片(不含...   19
11346  /content/drive/MyDrive/Tebame_第四組_機車辨識/裁剪照片(不含...   19
11347  /content/drive/MyDrive/Tebame_第四組_機車辨識/裁剪照片(不含...   19

[11348 rows x 2 columns]

#### 偷別人卷積網路 :
###### google keras application

In [ ]:
from tensorflow.keras.applications.vgg16 import VGG16  # 偷別人眼睛
basemodle = VGG16(weights='imagenet', include_top=False,input_shape=(224,224,3))
#basemodle.summary()

58900480/58889256 [==============================] - 1s 0us/step


##### 高參數 =>訓練資料要多
##### 低參數 =>訓練資料要少

#####開始疊層數

In [ ]:
from tensorflow.keras.models import Model, Sequential
from tensorflow.keras.layers import Dense, BatchNormalization, Layer, GlobalAvgPool2D, LeakyReLU, Conv2D
for i in basemodle.layers:
  i.trainable = False
basemodle.summary()

Model: "vgg16"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         [(None, 224, 224, 3)]     0         
_________________________________________________________________
block1_conv1 (Conv2D)        (None, 224, 224, 64)      1792      
_________________________________________________________________
block1_conv2 (Conv2D)        (None, 224, 224, 64)      36928     
_________________________________________________________________
block1_pool (MaxPooling2D)   (None, 112, 112, 64)      0         
_________________________________________________________________
block2_conv1 (Conv2D)        (None, 112, 112, 128)     73856     
_________________________________________________________________
block2_conv2 (Conv2D)        (None, 112, 112, 128)     147584    
_________________________________________________________________
block2_pool (MaxPooling2D)   (None, 56, 56, 128)       0     

In [ ]:
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Dense, BatchNormalization, Layer, GlobalMaxPool2D, LeakyReLU, Conv2D, Input, Concatenate, Add, AveragePooling2D, Dense, MaxPool2D

selfmodelinput = Input(shape=(224,224,3))
conv1x1_0_0 = Conv2D(29,1,padding="same",activation=LeakyReLU(alpha=0.25),strides=2)(selfmodelinput)
conv4x4_0_0 = Conv2D(32,4,padding="same",activation=LeakyReLU(alpha=0.25),strides=2)(selfmodelinput)
conv4x4_0_1 = Conv2D(32,4,padding="same",activation=LeakyReLU(alpha=0.25),strides=2)(selfmodelinput)
conv4x4_0_2 = Conv2D(32,4,padding="same",activation=LeakyReLU(alpha=0.25),strides=1)(conv4x4_0_1)
avgpool0 = AveragePooling2D(pool_size=(2,2))(selfmodelinput)
concat0 = Concatenate(axis=-1)([conv1x1_0_0,avgpool0])
add0 = Add()([conv4x4_0_0,conv4x4_0_2,concat0])
bn0 = BatchNormalization(axis=-1)(add0)
conv1x1_1_0 = Conv2D(12,1,padding="same",activation=LeakyReLU(alpha=0.25),strides=2)(bn0)
conv4x4_1_0 = Conv2D(10,4,padding="same",activation=LeakyReLU(alpha=0.25),strides=2)(bn0)
conv4x4_1_1 = Conv2D(10,4,padding="same",activation=LeakyReLU(alpha=0.25),strides=2)(bn0)
conv4x4_1_2 = Conv2D(10,4,padding="same",activation=LeakyReLU(alpha=0.25),strides=1)(conv4x4_1_1)
avgpool1 = AveragePooling2D(pool_size=(2,2))(bn0)
concat1 = Concatenate(axis=-1)([conv1x1_1_0,conv4x4_1_0,conv4x4_1_2])
add1 = Add()([avgpool1,concat1])
bn1 = BatchNormalization(axis=-1)(add1)
conv1x1_2_0 = Conv2D(12,1,padding="same",activation=LeakyReLU(alpha=0.25),strides=2)(bn1)
conv4x4_2_0 = Conv2D(10,4,padding="same",activation=LeakyReLU(alpha=0.25),strides=2)(bn1)
conv4x4_2_1 = Conv2D(10,4,padding="same",activation=LeakyReLU(alpha=0.25),strides=2)(bn1)
conv4x4_2_2 = Conv2D(10,4,padding="same",activation=LeakyReLU(alpha=0.25),strides=1)(conv4x4_2_1)
avgpool2 = AveragePooling2D(pool_size=(2,2))(bn1)
concat2 = Concatenate(axis=-1)([conv1x1_2_0,conv4x4_2_0,conv4x4_2_2])
add2 = Add()([avgpool2,concat2])
bn2 = BatchNormalization(axis=-1)(add2)
conv1x1_3_0 = Conv2D(12,1,padding="same",activation=LeakyReLU(alpha=0.25),strides=2)(bn2)
conv4x4_3_0 = Conv2D(10,4,padding="same",activation=LeakyReLU(alpha=0.25),strides=2)(bn2)
conv4x4_3_1 = Conv2D(10,4,padding="same",activation=LeakyReLU(alpha=0.25),strides=2)(bn2)
conv4x4_3_2 = Conv2D(10,4,padding="same",activation=LeakyReLU(alpha=0.25),strides=1)(conv4x4_3_1)
avgpool3 = AveragePooling2D(pool_size=(2,2))(bn2)
avgpool3_0 = AveragePooling2D(pool_size=(16,16))(selfmodelinput)
concat3 = Concatenate(axis=-1)([conv1x1_3_0,conv4x4_3_0,conv4x4_3_2])
add3 = Add()([avgpool3,concat3])
concat3_0 = Concatenate(axis=-1)([add3,avgpool3_0])
bn3 = BatchNormalization(axis=-1)(concat3_0)
conv1x1_4_0 = Conv2D(12,1,padding="same",activation=LeakyReLU(alpha=0.25),strides=2)(bn3)
conv4x4_4_0 = Conv2D(12,4,padding="same",activation=LeakyReLU(alpha=0.25),strides=2)(bn3)
conv4x4_4_1 = Conv2D(11,4,padding="same",activation=LeakyReLU(alpha=0.25),strides=2)(bn3)
conv4x4_4_2 = Conv2D(11,4,padding="same",activation=LeakyReLU(alpha=0.25),strides=1)(conv4x4_4_1)
avgpool4 = AveragePooling2D(pool_size=(2,2))(bn3)
concat4 = Concatenate(axis=-1)([conv1x1_4_0,conv4x4_4_0,conv4x4_4_2])
add4 = Add()([avgpool4,concat4])
bn4 = BatchNormalization(axis=-1)(add4)
gp = GlobalMaxPool2D()(bn4)

conv3x3_e_0_0 = Conv2D(16,3,padding="same",activation=LeakyReLU(alpha=0.25),strides=1)(selfmodelinput)
conv3x3_e_0_1 = Conv2D(16,3,padding="same",activation=LeakyReLU(alpha=0.25),strides=2)(conv3x3_e_0_0)
bn_e0 = BatchNormalization(axis=-1)(conv3x3_e_0_1)
conv3x3_e_1_0 = Conv2D(16,3,padding="same",activation=LeakyReLU(alpha=0.25),strides=1)(bn_e0)
conv3x3_e_1_1 = Conv2D(16,3,padding="same",activation=LeakyReLU(alpha=0.25),strides=2)(conv3x3_e_1_0)
maxpool_e_1_1 = MaxPool2D(pool_size=(2,2))(bn_e0)
add_e_1 = Add()([conv3x3_e_1_1,maxpool_e_1_1])
bn_e1 = BatchNormalization(axis=-1)(add_e_1)
conv3x3_e_2_0 = Conv2D(16,3,padding="same",activation=LeakyReLU(alpha=0.25),strides=1)(bn_e1)
conv3x3_e_2_1 = Conv2D(16,3,padding="same",activation=LeakyReLU(alpha=0.25),strides=2)(conv3x3_e_2_0)
maxpool_e_2_1 = MaxPool2D(pool_size=(2,2))(bn_e1)
add_e_2 = Add()([conv3x3_e_2_1,maxpool_e_2_1])
bn_e2 = BatchNormalization(axis=-1)(add_e_2)
conv3x3_e_3_0 = Conv2D(16,3,padding="same",activation=LeakyReLU(alpha=0.25),strides=1)(bn_e2)
conv3x3_e_3_1 = Conv2D(16,3,padding="same",activation=LeakyReLU(alpha=0.25),strides=2)(conv3x3_e_3_0)
maxpool_e_3_1 = MaxPool2D(pool_size=(2,2))(bn_e2)
add_e_3 = Add()([conv3x3_e_3_1,maxpool_e_3_1])
bn_e3 = BatchNormalization(axis=-1)(add_e_3)
conv3x3_e_4_0 = Conv2D(16,3,padding="same",activation=LeakyReLU(alpha=0.25),strides=1)(bn_e3)
conv3x3_e_4_1 = Conv2D(16,3,padding="same",activation=LeakyReLU(alpha=0.25),strides=2)(conv3x3_e_4_0)
maxpool_e_4_1 = MaxPool2D(pool_size=(2,2))(bn_e3)
add_e_4 = Add()([conv3x3_e_4_1,maxpool_e_4_1])
bn_e4 = BatchNormalization(axis=-1)(add_e_4)
gp1 = GlobalMaxPool2D()(bn_e4)

concat_all = Concatenate(axis=-1)([gp,gp1])
alk = Dense(20, activation="softmax")(concat_all)
selfmymodel = Model(inputs=[selfmodelinput],outputs=[alk])
selfmymodel.summary()

Model: "model_11"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_16 (InputLayer)           [(None, 224, 224, 3) 0                                            
__________________________________________________________________________________________________
conv2d_308 (Conv2D)             (None, 112, 112, 32) 1568        input_16[0][0]                   
__________________________________________________________________________________________________
conv2d_306 (Conv2D)             (None, 112, 112, 29) 116         input_16[0][0]                   
__________________________________________________________________________________________________
average_pooling2d_79 (AveragePo (None, 112, 112, 3)  0           input_16[0][0]                   
___________________________________________________________________________________________

In [ ]:
layers = [
          BatchNormalization(),
          GlobalAvgPool2D(),
          Dense(128, activation=LeakyReLU(alpha=0.25)),
          Dense(20, activation="softmax")
]
mymodel = Sequential(layers)
modle= Model(inputs=basemodle.input,outputs = mymodel(basemodle.output))
modle.summary()

Model: "model"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         [(None, 224, 224, 3)]     0         
_________________________________________________________________
block1_conv1 (Conv2D)        (None, 224, 224, 64)      1792      
_________________________________________________________________
block1_conv2 (Conv2D)        (None, 224, 224, 64)      36928     
_________________________________________________________________
block1_pool (MaxPooling2D)   (None, 112, 112, 64)      0         
_________________________________________________________________
block2_conv1 (Conv2D)        (None, 112, 112, 128)     73856     
_________________________________________________________________
block2_conv2 (Conv2D)        (None, 112, 112, 128)     147584    
_________________________________________________________________
block2_pool (MaxPooling2D)   (None, 56, 56, 128)       0     

##### 模型 compile

In [ ]:
from tensorflow.keras.losses import SparseCategoricalCrossentropy
modle.compile(
        loss=SparseCategoricalCrossentropy(),
        optimizer="adam",
        metrics=["accuracy"]
)

In [ ]:
from tensorflow.keras.losses import SparseCategoricalCrossentropy
selfmymodel.compile(
        loss=SparseCategoricalCrossentropy(),
        optimizer="adam",
        metrics=["accuracy"]
)

###### 先看一下圖片

In [ ]:
import random
import matplotlib.pyplot as plt
from PIL import Image
import numpy as np
# import 匯入 當初預處理的方式
from tensorflow.keras.applications.inception_resnet_v2 import preprocess_input 
p = df["path"]
idx = random.randint(0, len(p)-1)
img = Image.open(p[idx]).resize((224, 224)).convert("RGB")
img_np = np.array(img)
img_np_pre = preprocess_input(img_np)
print(img_np_pre)
plt.imshow(img)

In [ ]:
p

0        /content/drive/MyDrive/Tebame_第四組_機車辨識/原始照片(含外...
1        /content/drive/MyDrive/Tebame_第四組_機車辨識/原始照片(含外...
2        /content/drive/MyDrive/Tebame_第四組_機車辨識/原始照片(含外...
3        /content/drive/MyDrive/Tebame_第四組_機車辨識/原始照片(含外...
4        /content/drive/MyDrive/Tebame_第四組_機車辨識/原始照片(含外...
                               ...                        
11343    /content/drive/MyDrive/Tebame_第四組_機車辨識/裁剪照片(不含...
11344    /content/drive/MyDrive/Tebame_第四組_機車辨識/裁剪照片(不含...
11345    /content/drive/MyDrive/Tebame_第四組_機車辨識/裁剪照片(不含...
11346    /content/drive/MyDrive/Tebame_第四組_機車辨識/裁剪照片(不含...
11347    /content/drive/MyDrive/Tebame_第四組_機車辨識/裁剪照片(不含...
Name: path, Length: 11348, dtype: object

### generator

In [ ]:
x = np.array(df["path"])
y = np.array(df["ans"])

In [ ]:
def data_generator(x, y, batch_size=19):
  while True:
    idx = np.random.randint(0, len(x), size=batch_size)
    x_batch, y_batch = x[idx], y[idx]
    x_final = []
    for path in x_batch:
      img = Image.open(path).resize((224, 224)).convert("RGB")    #  開啟路徑圖檔並改大小、轉成RGB
      img_pre = preprocess_input(np.array(img))              # 轉成陣列再預處理
      x_final.append(img_pre)            
    x_final = np.array(x_final)
    y_batch = np.array(y_batch)
    yield (x_final, y_batch)
gen = data_generator(x, y)
x_gen, y_gen = gen.__next__()
print(x_gen.shape)
print(y_gen.shape)
print(x_gen)
print(y_gen)


(19, 224, 224, 3)
(19,)
[[[[-0.10588235 -0.3490196  -0.45098037]
   [-0.10588235 -0.31764704 -0.45098037]
   [-0.03529412 -0.12156862 -0.15294117]
   ...
   [ 0.32549024  0.41960788  0.33333337]
   [ 0.27058828  0.34901965  0.27843142]
   [ 0.22352946  0.30196083  0.2313726 ]]

  [[-0.06666666 -0.30196077 -0.44313723]
   [-0.0745098  -0.2862745  -0.44313723]
   [-0.04313725 -0.15294117 -0.20784312]
   ...
   [ 0.10588241  0.17647064  0.12941182]
   [ 0.10588241  0.18431377  0.12941182]
   [ 0.10588241  0.19215691  0.12156868]]

  [[-0.00392157 -0.2235294  -0.38823527]
   [-0.05098039 -0.27058822 -0.42745095]
   [-0.09019607 -0.21568626 -0.2862745 ]
   ...
   [ 0.14509809  0.20000005  0.12156868]
   [ 0.14509809  0.20784318  0.12941182]
   [ 0.15294123  0.21568632  0.13725495]]

  ...

  [[-0.5294118  -0.5294118  -0.5137255 ]
   [-0.52156866 -0.5294118  -0.5137255 ]
   [-0.5058824  -0.52156866 -0.5058824 ]
   ...
   [ 0.5686275   0.58431375  0.54509807]
   [ 0.54509807  0.58431375  0.53

In [ ]:
from sklearn.model_selection import train_test_split

 # gp + vivo + gryphus6 + SR + DRG + FIDDLE + S2
group_tol = [[0] for i in range(20)]
group_tr = [[0] for i in range(20)]
group_te = [[0] for i in range(20)]
indexcontrastvalue = [gp, vivo, gryphus6, SR, SL, JOG, BWS, LIMI, LIKE, DRG, FIDDLE, S2, S3, VIVAMIX, xml125, JH, KRV, MANY, Force, xdj]

x_train = []
y_train = []
x_test = []
y_test = []
print(type(indexcontrastvalue[0]))
#print(len(indexcontrastvalue[0]))
for i in range(20):
  #print(i)
  group_tol[i] = np.random.choice(indexcontrastvalue[i], len(indexcontrastvalue[i]), replace=False)
  group_tr[i], group_te[i] = train_test_split(group_tol[i], test_size=0.1)
  x_train = np.concatenate((x_train, group_tr[i]))
  y_train = y_train + ([i] * len(group_tr[i]))
  x_test = np.concatenate((x_test,group_te[i]))
  y_test = y_test + ([i] * len(group_te[i]))
y_train = np.array(y_train)
y_test = np.array(y_test)



print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)
print(type(x_test))
type(y_test)

<class 'list'>
(10204,)
(1144,)
(10204,)
(1144,)
<class 'numpy.ndarray'>


numpy.ndarray

In [ ]:
train_generator = data_generator(x_train, y_train)
test_generator = data_generator(x_test, y_test)

In [ ]:
from tensorflow.keras.callbacks import EarlyStopping, ModelCheckpoint
callbacks = [
             EarlyStopping(patience=5, restore_best_weights=True),
             ModelCheckpoint("myall.h5", save_best_only=True)
]

selfmymodel.fit_generator(
    train_generator,
    steps_per_epoch=20,
    epochs=100,
    validation_data=test_generator,
    validation_steps=2, 
    callbacks=callbacks
                    )

/usr/local/lib/python3.7/dist-packages/keras/engine/training.py:1972: UserWarning: `Model.fit_generator` is deprecated and will be removed in a future version. Please use `Model.fit`, which supports generators.
  warnings.warn('`Model.fit_generator` is deprecated and '


Epoch 1/100
20/20 [==============================] - 48s 3s/step - loss: 1.9195 - accuracy: 0.4500 - val_loss: 2.1997 - val_accuracy: 0.3684


/usr/local/lib/python3.7/dist-packages/keras/utils/generic_utils.py:497: CustomMaskWarning: Custom mask layers require a config and must override get_config. When loading, the custom mask layer must be passed to the custom_objects argument.
  category=CustomMaskWarning)


Epoch 2/100
20/20 [==============================] - 48s 3s/step - loss: 1.9415 - accuracy: 0.4316 - val_loss: 2.0789 - val_accuracy: 0.3158
Epoch 3/100
20/20 [==============================] - 47s 2s/step - loss: 1.8665 - accuracy: 0.4237 - val_loss: 2.5349 - val_accuracy: 0.3158
Epoch 4/100
20/20 [==============================] - 47s 2s/step - loss: 1.9528 - accuracy: 0.4026 - val_loss: 1.5593 - val_accuracy: 0.5263
Epoch 5/100
20/20 [==============================] - 51s 3s/step - loss: 1.8861 - accuracy: 0.4368 - val_loss: 1.8525 - val_accuracy: 0.4211
Epoch 6/100
20/20 [==============================] - 47s 2s/step - loss: 1.8372 - accuracy: 0.4579 - val_loss: 2.2302 - val_accuracy: 0.2632
Epoch 7/100
 7/20 [=========>....................] - ETA: 25s - loss: 1.9430 - accuracy: 0.4060

In [ ]:
selfmymodel.evaluate_generator(test_generator, steps=1)

/usr/local/lib/python3.7/dist-packages/keras/engine/training.py:2006: UserWarning: `Model.evaluate_generator` is deprecated and will be removed in a future version. Please use `Model.evaluate`, which supports generators.
  warnings.warn('`Model.evaluate_generator` is deprecated and '


[2.348963737487793, 0.2631579041481018]

In [ ]:
selfmymodel.save("selfmymodel_5_e5_allclass_run4.h5")

/usr/local/lib/python3.7/dist-packages/keras/utils/generic_utils.py:497: CustomMaskWarning: Custom mask layers require a config and must override get_config. When loading, the custom mask layer must be passed to the custom_objects argument.
  category=CustomMaskWarning)


In [ ]:

from tensorflow.keras.callbacks import EarlyStopping, ModelCheckpoint
callbacks = [
             EarlyStopping(patience=5, restore_best_weights=True),
             ModelCheckpoint("scooterall.h5", save_best_only=True)
]

modle.fit_generator(
    train_generator,
    steps_per_epoch=20,
    epochs=100,
    validation_data=test_generator,
    validation_steps=2, 
    callbacks=callbacks
                    )

In [ ]:
modle.save("VGG16_allclass_V2_run3.h5")

In [ ]:
from tensorflow.keras.models import load_model
modle = load_model("/content/VGG16_allclass.h5")

In [ ]:
modle.evaluate_generator(test_generator, steps=1)

/usr/local/lib/python3.7/dist-packages/keras/engine/training.py:2006: UserWarning: `Model.evaluate_generator` is deprecated and will be removed in a future version. Please use `Model.evaluate`, which supports generators.
  warnings.warn('`Model.evaluate_generator` is deprecated and '


[0.41217660903930664, 0.8947368264198303]

In [ ]:
import requests
from PIL import Image
url = input("輸入網址")
response = requests.get(url, stream=True, verify=False)
img = Image.open(response.raw).resize((224,224))
img_np = preprocess_input(np.array(img))
print("預測:", modle.predict([[img_np]]))
plt.imshow(img, cmap="gray")

輸入網址https://cdn2.ettoday.net/images/3780/d3780165.jpg


/usr/local/lib/python3.7/dist-packages/urllib3/connectionpool.py:847: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)


ValueError: ignored

In [ ]:
ori_imgs = []
for p in x_test:
    img = Image.open(p).resize((224, 224)).convert("RGB")
    ori_imgs.append(np.array(img))
ori_imgs = np.array(ori_imgs)
preprocess_imgs = preprocess_input(ori_imgs)

pre = model.predict(preprocess_imgs)



NameError: ignored

In [ ]:
pre = pre.argmax(axis=1)

In [ ]:
trans = ["gp", "vivo", "gryphus6", "SR", "DRG", "FIDDLE", "S2"]
 # gp + vivo + gryphus6 + SR + DRG + FIDDLE + S2
idx = np.nonzero(pre != y_test)[0]
pre_false_img = ori_imgs[idx]
pre_false_val = pre[idx]
pre_false_ori = y_test[idx]

plt.figure(figsize=(15, 15))
width = 10
height = len(idx) // width + 1
for i in range(len(idx)):
    plt.subplot(height, width, i+1)
    t = "[O]:{}\n[P]:{}".format(trans[pre_false_ori[i]],
                                trans[pre_false_val[i]])
    plt.title(t)
    plt.axis("off")
    plt.imshow(pre_false_img[i])


In [ ]:
import pandas as pd
from sklearn.metrics import confusion_matrix
mat = confusion_matrix(y_test, pre)
pd.DataFrame(
        mat,
        index=["{}(正確)".format(trans[i]) for i in range(7)],
        columns=["{}(預測)".format(trans[i]) for i in range(7)]
)

In [ ]:
import requests
url = input("Enter:")
response = requests.get(url, stream=True, verify=False)
img = Image.open(response.raw).resize((224, 224)).convert("RGB")
img_np = preprocess_input(np.array(img).reshape(1, 224, 224, 3))
proba = model.predict(img_np)
ans = proba.argmax(axis=1)
print("預測:", trans[ans[0]])
print("機率:", proba[0])
plt.imshow(img)
#trans = ["gp", "vivo", "gryphus6", "SR", "DRG", "FIDDLE", "S2"]

In [ ]:
#01:33:12